### ISSUE TITLE
MAS fails to start when using a custom hostname

### ISSUE THREAD

**Issue by klusark** [CAAPIM/Docker-MAS#26]
If I use the environment variables specified in the README I get the error

```
mas_1                | Liquibase Update Successful
mas_1                | liquibase-otk-db.sh: Created otk_db database on mysqldb
mas_1                | Unexpected error running Liquibase: Validation Failed:
mas_1                |      1 change sets check sum
mas_1                |           /db/liquibase/otk-dev-console.xml::developer-console-access::gateway is now: 7:35ed6133b234d8b20b7678194c52eee8
mas_1                |
mas_1                |
mas_1                |
mas_1                | ERROR - liquibase-otk-db.sh: Failed to create or update the OAuth Client for the Developer Console!
dockermas_mas_1 exited with code 1
```

If I unset BUNDLE_TEMPLATE_OTK_HOSTNAME everything comes up correctly on my domain, however when I login to the oauth server it redirects me to https://mas, as you'd expect from the default OTK hostname.

**Comment by kazvictor** [comment]
Changing hostnames is not currently supported with an existing database. You will have to drop your volume when changing hostnames. In order to do that:
```
docker-compose rm
docker volume rm dockermasgithub_mysql-data
```
> Note your volume might be called something slightly different

Once that is done you can then start the images again `docker-compose up`

This is a limitation we definitely want to address in future versions. I'll leave this issue open until it is removed.

**Comment by kazvictor** [comment]
Documentation was added in pull request [27](https://github.com/CAAPIM/Docker-MAS/pull/27)

**Comment by kazvictor** [comment]
This should no longer be needed after #28 is merged.
